---
  - name: GET IP
    set_fact:
       vlanid: "{{ server['network']['nic'][0]['vlan'] }}"
       ip_address: "192.168.18.179"
       netmask: "255.255.255.192"
       gateway: "192.168.18.129"
       dns_server1: "192.168.18.150"
       dns_server2: "192.168.18.151"
       vlanname : "XaaS|AP|epg_XaaS_DMZ_HCM"
    when: index | int == 0

  - name: GET IP
    set_fact:
       vlanid: "{{ server['network']['nic'][0]['vlan'] }}"
       ip_address: "192.168.18.180"
       netmask: "255.255.255.192"
       gateway: "192.168.18.129"
       dns_server1: "192.168.18.150"
       dns_server2: "192.168.18.151"
       vlanname : "XaaS|AP|epg_XaaS_DMZ_HCM"
    when: index | int == 1

  - debug:
        msg : "CI created with following details {{ server['name'] }} {{ip_address}}"    

  - name: Check if VM Exists
    community.vmware.vmware_vm_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      vm_name: '{{ server['name'] }}'
      validate_certs: false
    delegate_to: localhost
    register: vm_info
    when: false

  - block: 

    - name: Create the VM
      vmware_guest:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        cluster: '{{ cluster }}'
        datacenter: '{{ datacenter }}'
        folder: '{{ folder }}'
        name: '{{ server['name'] }}'
        state: poweredon
        annotation: "Created by Ansible"
        disk:
        - size_gb: 150
          type: thin
          autoselect_datastore: true
        networks:
        - name: '{{ vlanname }}'
          type: static
          ip: '{{ ip_address }}'
          netmask: '{{ netmask }}'
          gateway: '{{ gateway }}'
          dns_servers:
            - '{{ dns_server1 }}'
            - '{{ dns_server2 }}'
        hardware:
          memory_mb: '{{ memory }}'
          num_cpus: '{{ cpu }}'
          hotadd_cpu: true
          hotadd_memory: true
        customization:
          dns_servers:
            - '{{ dns_server1 }}'
            - '{{ dns_server2 }}'
          domain : '{{ ad_domain }}'
          hostname: '{{ server['name'] }}'
        template: '{{ templatename }}'
        wait_for_ip_address: yes
        wait_for_ip_address_timeout: 600

    - set_fact:
          ci_update: "{{server['name']}}-{{ip_address}}-{{memory}}-{{cpu}}-{{requestor}}"
          
    - debug:
          msg : "CI created with following details {{ ci_update }}"

    when: false