---
 - include_tasks: readvars.yml

 - include_tasks: parsevars.yml

 - include_tasks: mainoperation.yml
   loop: "{{servers}}"
   loop_control:
      loop_var: server
      index_var: index
   register: mainoperation
