---
  - name: Parse User Manifest
    set_fact:
       ad_domain: '{{usermanifest["ad_domain"]}}'
       application_code: '{{usermanifest["application_code"]}}'
       application_service_id: '{{usermanifest["application_service_id"]}}'
       application_service_name: '{{usermanifest["application_service_name"]}}'
       environment: '{{usermanifest["environment"]}}'
       requestor: '{{usermanifest["requestor"]}}'
       dcs_type: '{{usermanifest["dcs_type"]}}'
       rdr_class: '{{usermanifest["rdr_class"]}}'
       cpu: '{{usermanifest["cpu"]}}'
       memory: '{{usermanifest["memory"][0:-1] | int * 1024 }}'
       environment_zone: '{{usermanifest["environment_zone"]}}'
       software_family: '{{usermanifest["software_family"]}}'
       server_type: '{{usermanifest["server_type"]}}'
       options: '{{usermanifest["options"]}}'
       servers: '{{usermanifest["servers"]}}'

  - set_fact: 
       cluster: 'cluster'
    when: 'Production' in  environment

  - set_fact: 
       cluster: 'cluster'
    when: 'Production' not in  environment


  - set_fact: 
       templatename: "Rhel7image-testing"
    when: 'rhel8-std' in  software_family

  - set_fact: 
       templatename: "Rhel7image-testing"
    when: 'rhel8-std' in  software_family